### ISSUE TITLE
Taking markdown messages seriously

### ISSUE THREAD

**Issue by c42f** [c42f/TerminalLoggers.jl#16]
The stdlib Logging docs have long [stated](https://docs.julialang.org/en/v1/stdlib/Logging/#Log-event-structure-1) that

> By convention AbstractStrings passed as messages are assumed to be in markdown format.

I suggest we take this seriously and actually render them as markdown, by

1. If the `message` is an abstract string, use `Markdown.parse` to parse the string
2. Use `Markdown.term()` to format it
3. Do some munging to wrap the result in the normal box drawing characters on the left hand side (this bit is actually quite ugly in implementation, and is the reason I've never followed through on this before).
4. Try it for a while and see whether this works well in practice. If it does, put it into `ConsoleLogger` to establish a strong convention.

It might be argued that we may be a bit aggressive in interpreting *all* AbstractStrings as markdown and that the backend could misrepresent messages this way to the user. I'm kind of inclined to try it and see, but an alternative would be to wrap log strings in a type to indicate to the backend that special treatment is required.  Kind of like `@md_str` but with lazy parsing so that no actual work happens in the frontend.

Thoughts?

**Comment by c42f** [comment]
By the way, I feel this would be neatly consistent with the way that julia docstrings work. That was an opinionated choice which "just works" once people got used to it. (Key to that working ecosystem-wide would be having a strong default in Base.)

**Comment by tkf** [comment]
I've been wanting to suggest this too. I'm :+1: for just try the aggressive version and see how it works.

> 2\. Use `Markdown.term()` to format it

How about just using text/plain `show`?  It'd be something like

```julia
if message isa AbstractString
    message = Markdown.parse(message)
end
formatted = sprint(show, MIME"text/plain"(), message, context=???)
```

This way, non-`AbstractString` would be pretty-printed as well (e.g., `Markdown.MD`).

BUT, this is actually incompatible with what we just added to the documentation https://github.com/JuliaLang/julia/pull/34568. As it's not released yet  https://github.com/JuliaLang/julia/commit/cc47f8731472adac7984857df8ba4f7924146293, maybe it makes sense to tweak the documentation to add some freedom for the custom loggers?

Also, there is a question of what we should pass to `context=`.  In particular, what `:displaysize` should we pass?  It's complicated because there is no uniform `:displaysize` for multi-line `message`:

```
┌ Info: ... first line ...
└ ... second line ...
```

Maybe we should pass

```julia
rows, cols = displaysize(logger.stream)
context = IOContext(logger.stream, :displaysize => (rows, cols - 2))
```

and use

```
┌ Info:
│ ... first line ...
└ ... second line ...
```

if the formatted message contains multiple lines _or_ its length exceeds `cols - 2`?

**Comment by tkf** [comment]
Note that the use of `text/plain` would be compatible of how key-value pairs are formatted.  It's a bit inconsistent ATM that only the "main message" is formatted with 2-arg `show` (via `print`)

```
julia> @info ones(2, 2) ones(2, 2)
┌ Info: [1.0 1.0; 1.0 1.0]
│   ones(2, 2) =
│    2×2 Array{Float64,2}:
│     1.0  1.0
└     1.0  1.0
```

**Comment by c42f** [comment]
> In particular, what :displaysize should we pass?

This problem is actually the main reason such a feature never made it into Base!

I think some changes to `Markdown` could be helpful (eg, to control the margin) but for the meantime I was playing with a horrible hack: call `Markdown.term(io, Markdown.parse(prefix*"\n"*message))`, then delete the prefix from that string before adding it back in with the other formatting :grimacing: 

> if the formatted message contains multiple lines _or_ the length of the message combined with the prefix exceeds `cols - 2`?

This might be fine/better in practice. Determining lengths is a bit annoying given the presence of ANSI codes but there's already some hacks present for that.
